### PR TITLE
ZmP Mergeup 20190306

### PR DESCRIPTION
**Pull request by mike-scott**

### CODE REVIEW

**Comment by mbolivar** [comment]
Re: `06ee6d4514 ([FIO squash] net: lwm2m: only trigger new persist values once)`: `squash` is not a valid sauce tag. Did you mean something like `[FIO saucetag] squash! net: lwm2m: only trigger new persist values once`?

Just noticed the use of this, though `squash` has been used as a sauce tag in earlier commits.

**Comment by mike-scott** [comment]
> Did you mean something like [FIO saucetag] squash! net: lwm2m: only trigger new persist values once

@mbolivar Yeah, I looked up the saucetags and noticed we were missing squash and then guessed.  It's been reverted and squashed now with this mergeup.  I'll do better next time.

**Comment by mike-scott** [comment]
ci-retest

**Comment by mike-scott** [comment]
ci-retest

**Pull request merged**
