### PR TITLE
Mergeup 20190214 / 20190216

### PR DESCRIPTION
**Pull request by mike-scott**

### CODE REVIEW

**Comment by mbolivar** [comment]
LGTM but maybe we want to use this to shake out CI some more?

FOTA and sanity both have these errors:

```
== 2019-02-19 15:20:50 Installing dependencies
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pyudev'
```

```
149/149 nrf52_blenano2            tests/ztest/test/base/testing.ztest.verbose_1      PASSED
148 of 149 tests passed with 0 warnings in 1392 seconds
Traceback (most recent call last):
  File "/repo/scripts/sanitycheck", line 3395, in <module>
    main()
  File "/repo/scripts/sanitycheck", line 3385, in main
    ts.testcase_report(LAST_SANITY)
  File "/repo/scripts/sanitycheck", line 2639, in testcase_report
    rowdict["ram_size"] = goal.metrics["ram_size"]
KeyError: 'ram_size'
```

FOTA additionally has this one:

```
 99/149 nrf52_blenano2            tests/kernel/mem_slab/mslab_threadsafe/kernel.memory_slabs FAILED: timeout
../tmp/outdir/nrf52_blenano2/tests/kernel/mem_slab/mslab_threadsafe/kernel.memory_slabs/handler.log-
```

**Comment by mbolivar** [comment]
@doanac ^^

**Comment by doanac** [comment]
@mbolivar - the pyudev is fine. That's the check i do to see if i need to install it or not. The ram_size is fine also. I think I need to create a new patch to sanitycheck to deal with that. I'm running with my sanitycheck PR for "--test-only" and that logic seems to cause this missing key which I assume is created when you compile the source.

**Comment by mbolivar** [comment]
@doanac I'm confused about why the test says it failed if that is fine?

**Comment by doanac** [comment]
@mbolivar, there's a real sanity failure here: https://ci.foundries.io/projects/zephyr/builds/4905/sanity-test-nrf52/tests/

**Comment by mike-scott** [comment]
@doanac @mbolivar I'm trying to bisect the mslab_threadsafe test and it's so flaky that it's a bear.  I can try the test 30-40 times with success and then get 3 failures in a row.

**Pull request merged**
